[package]
name = "discord-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12.4"
cassandra-cpp = "3.0.2"
tokio = { version = "1.44.2", features = ["full", "macros", "rt-multi-thread"] }
rustble = {path = "../rustble"}
rand = "0.9.0"
itertools = "0.14.0"
